-- =============================================================================
-- SIMPLIFIED BOOKS E-COMMERCE DATABASE SCHEMA
-- Easy to understand and use - No complex features
-- =============================================================================

-- =============================================================================
-- BOOKS TABLE
-- =============================================================================
create table books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  price numeric(10,2) not null check (price >= 0),
  original_price numeric(10,2) check (original_price >= price),
  category text not null check (category in ('Self Development', 'Finance', 'Leadership')),
  image_url text,
  description text,
  in_stock boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- =============================================================================
-- COMBOS TABLE
-- =============================================================================
create table combos (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  book_ids bigint[] not null, -- Array of book IDs in this combo
  price numeric(10,2) not null check (price >= 0),
  original_price numeric(10,2) check (original_price >= price),
  image_url text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- =============================================================================
-- PROFILES TABLE (User Profile Information)
-- =============================================================================
create table profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  email text,
  full_name text,
  phone text,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- =============================================================================
-- ORDERS TABLE
-- =============================================================================
create table orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id), -- Optional: Link to logged-in user
  customer_name text not null,
  customer_phone text not null,
  address text not null,
  total_amount numeric(10,2) not null check (total_amount >= 0),
  items_json jsonb not null, -- Stores cart items
  status text check (status in ('Pending', 'Confirmed', 'Delivered', 'Cancelled')) default 'Pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- =============================================================================
-- ENABLE ROW LEVEL SECURITY
-- =============================================================================
alter table books enable row level security;
alter table combos enable row level security;
alter table profiles enable row level security;
alter table orders enable row level security;

-- =============================================================================
-- SECURITY POLICIES (Simple & Safe)
-- =============================================================================

-- Books: Everyone can read books
create policy "Anyone can view books" on books
  for select using (true);

-- Combos: Everyone can read active combos
create policy "Anyone can view combos" on combos
  for select using (true);

-- Profiles: Users can view their own profile
create policy "Users can view own profile" on profiles
  for select using (auth.uid() = id);

-- Profiles: Users can update their own profile
create policy "Users can update own profile" on profiles
  for update using (auth.uid() = id);

-- Profiles: System can insert profiles (via trigger)
create policy "Enable insert for authenticated users" on profiles
  for insert with check (auth.uid() = id);

-- Orders: Anyone can create an order (guest checkout supported)
create policy "Anyone can create orders" on orders
  for insert with check (true);

-- Orders: Users can view their own orders
create policy "Users can view own orders" on orders
  for select using (
    auth.uid() = user_id OR user_id IS NULL
  );

-- Orders: Users can cancel their own orders (only Pending/Confirmed status)
create policy "Users can cancel own orders" on orders
  for update using (
    auth.uid() = user_id AND 
    status IN ('Pending', 'Confirmed')
  )
  with check (
    status = 'Cancelled'
  );

-- =============================================================================
-- INDEXES FOR BETTER PERFORMANCE
-- =============================================================================

-- Speed up filtering by category
create index idx_books_category on books(category);

-- Speed up profile lookups
create index idx_profiles_email on profiles(email);

-- =============================================================================
-- AUTOMATIC PROFILE CREATION (Trigger Function)
-- =============================================================================

-- This function automatically creates a profile when a new user signs up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, created_at, updated_at)
  values (new.id, new.email, now(), now());
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function when a new user is created
-- Drop existing trigger if it exists
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Speed up filtering by stock status
create index idx_books_in_stock on books(in_stock);

-- Speed up filtering active combos
create index idx_combos_is_active on combos(is_active);

-- Speed up user's order history
create index idx_orders_user_id on orders(user_id);

-- Speed up sorting by price
create index idx_books_price on books(price);

-- =============================================================================
-- SAMPLE DATA (Optional - for testing)
-- =============================================================================

-- Uncomment below to insert sample books
/*
insert into books (title, author, price, original_price, category, image_url, description, in_stock) values
  ('Rich Dad Poor Dad', 'Robert Kiyosaki', 299, 499, 'Finance', '/books/richdad.jpg', 'Financial education book', true),
  ('Atomic Habits', 'James Clear', 399, 599, 'Self Development', '/books/atomic.jpg', 'Build good habits', true),
  ('Think and Grow Rich', 'Napoleon Hill', 249, 399, 'Finance', '/books/think.jpg', 'Success principles', true);
*/

-- =============================================================================
-- USAGE GUIDE
-- =============================================================================
--
-- That's it! Your database is ready to use.
--
-- ENVIRONMENT VARIABLES (.env):
-- VITE_SUPABASE_URL=your_project_url
-- VITE_SUPABASE_ANON_KEY=your_anon_key
--
-- COMMON QUERIES:
--
-- Get all books:
--   const { data } = await supabase.from('books').select('*')
--
-- Get books by category:
--   const { data } = await supabase.from('books').select('*').eq('category', 'Finance')
--
-- Create order:
--   const { data } = await supabase.from('orders').insert({
--     customer_name: 'John Doe',
--     customer_phone: '1234567890',
--     address: 'Street, City',
--     total_amount: 500,
--     items_json: cartItems,
--     user_id: user?.id // optional
--   })
--
-- Get user orders (if logged in):
--   const { data } = await supabase.from('orders').select('*').eq('user_id', user.id)
--
-- =============================================================================
